### ISSUE TITLE
Providing String as a argument causes crash

### ISSUE THREAD

**Issue by keinsell** [stepci/liquidless-faker#1]
I've tried multiple ways to pipe options to faker but cannot succeeded, when I do things like `{{ lorem.lines | fake: 1 }}` where argument is privitive things ten to work - but only when argument is integer; as soon as I will add string there is a crash.

Example: `${{ phone.number | fake: "+48#########" }}`

To be checked on https://stepci.com/ playground.

**Comment by mishushakov** [comment]
Playground was outdated. Feel free to reopen the issue if you're experiencing this on local

**Comment by HKandulla** [comment]
Hi @mishushakov ,
how can we pass objects to faker, as in `faker.color.cmyk({ format: 'css' })`
Thanks, Hannes

**Comment by mishushakov** [comment]
Like this?

`{{color.cmyk | fake: {"format": "css"}}}`

Keep in mind this is probably not possible to do in YAML, because of double quotes

**Comment by keinsell** [comment]
I would be interesting in knowing real example how I can pass the object to faker for example, like @HKandulla mentioned, `faker.color.cmyk({ format: 'css' })` inside of the `.yaml` test file that is run in stepci.

**Comment by keinsell** [comment]
> Playground was outdated. Feel free to reopen the issue if you're experiencing this on local

Problem is still persistent in playground and on my local machine, it's a real issue with stepci and how faker or liquidless is handled. And I cannot reopen the issue, can we cut the shit?

**Comment by mishushakov** [comment]
I have since added JSON5 support, you can now use single quotes for JSON objects:

```yaml
version: "1.1"
name: Fake Data
tests:
  example:
    steps:
      - name: GET request
        http:
          url: "https://en.wikipedia.org/wiki/${{color.cmyk | fake: {'format': 'css'}}}"
          method: GET
          check:
            status: /^20/
```

**Comment by keinsell** [comment]
Okay, that seems to work - however when I try to reference phone number format it does not :/

```yaml
version: "1.1"
name: Fake Data
tests:
  example:
    steps:
      - name: GET request
        http:
          url: "https://en.wikipedia.org/wiki/${{ phone.number | fake: '+48#########' }}"
          method: GET
          check:
            status: /^20/
```

At this point I have no clue it's issue with faker (where function works in faker library used in way it should be parsed), liquidless (it seems to pass things correctly) or liquidless-faker (where something on the road is wrong)
